config/routes.rb
Rails.application.routes.draw do
  # You can have the root of your site routed with "root"
  root 'twillio#index'
  put '/send_text', to: 'twillio#test'
  get '/mockup', to: 'mockup#index'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/mockup_controller.rb
# Class used for testing Twillio's API
class MockupController < ApplicationController
  def index
  end
end

app/controllers/twillio_controller.rb
# Class used for testing Twillio's API
class TwillioController < ApplicationController
  def index
  end

  def test
    # Get your Account Sid and Auth Token from twilio.com/user/account
    account_sid = ENV['twillio_access_id']
    auth_token = ENV['twillio_auth_token']
    
    begin
      @client = Twilio::REST::Client.new account_sid, auth_token
      
      @client.account.messages.create(body: params[:message],
        to: params[:number],     # Replace with your phone number
        from: "+16136930396")   # Replace with your Twilio number
    
    rescue Twilio::REST::RequestError => e
      flash[:notice] = e.message
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/twillio_helper.rb
module TwillioHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    
    <title>Waitlist Manager - Your ideal Waitlist Assistant</title>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
    <%= csrf_meta_tags %>
  </head>

  <body>

    <nav class="navbar navbar-fixed-top navbar-dark bg-inverse">
      <a class="navbar-brand" href="#">Waitlist Manager</a>
      <ul class="nav navbar-nav">
        <li class="nav-item active">
          <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">About</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Contact</a>
        </li>
      </ul>
    </nav>

    <div class="container">

      <%= yield %>

    </div><!-- /.container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  </body>
</html>

app/views/mockup/index.html.erb
<h1>Eldorado - Current Waitlist</h1>

<table class="table table-striped">
    <thead class="thead-inverse">
        <tr>
            <th>Guest's name</th>
            <th>Cellphone</th>
            <th>Party of</th>
            <th>Average waiting time</th>
            <th>&nbsp;</th>
        </tr>
    </thead>
    <tbody>
        <form>
        <tr class="table-success">
            <td>
                <input type="text" class="form-control" id="exampleInputEmail1" placeholder="Guest's name">
            </td>
            <td>
                <input type="phone" class="form-control" id="exampleInputEmail1" placeholder="Phone number">
            </td>
            <td>
                <select name="party" class="form-control">
                    <option></option>
                    <option>1</option>
                    <option>2</option>
                    <option>3</option>
                    <option>4</option>
                </select>
            </td>
            <td></td>
            <td>
                <button class="btn btn-success"><i class="fa fa-plus"></i></button>
            </td>
        </tr>
        </form>
        <!-- List -->
        <tr class="table-danger" style="font-weight: bold;">
            <td>
                Simon Blais
            </td>
            <td>
                819-962-7979
            </td>
            <td>
                3
            </td>
            <td>1m30s late</td>
            <td>
                <button class="btn btn-success"><i class="fa fa-check"></i></button>
                <button class="btn btn-danger"><i class="fa fa-trash"></i></button>
            </td>
        </tr>
        <tr class="table-warning">
            <td>
                Alexandre Voyer
            </td>
            <td>
                819-962-7979
            </td>
            <td>
                4
            </td>
            <td>30 mins</td>
            <td>
                <button class="btn btn-success"><i class="fa fa-check"></i></button>
                <button class="btn btn-warning">1m59s remaining...</button>
            </td>
        </tr>
        <tr>
            <td>
                Simon D'Aoust
            </td>
            <td>
                819-962-7979
            </td>
            <td>
                2
            </td>
            <td>30 mins</td>
            <td>
                <button class="btn btn-primary"><i class="fa fa-phone"></i></button>
                <button class="btn btn-danger"><i class="fa fa-trash"></i></button>
            </td>
        </tr>
        <tr>
            <td>
                Stéphane Lévesque
            </td>
            <td>
                819-962-7979
            </td>
            <td>
                2
            </td>
            <td>30 mins</td>
            <td>
                <button class="btn btn-primary"><i class="fa fa-phone"></i></button>
                <button class="btn btn-danger"><i class="fa fa-trash"></i></button>
            </td>
        </tr>
    </tbody>
</table>

app/views/twillio/index.html.erb
<h1>Send your text</h1>
<%= form_tag(send_text_path, method: :put) do |f| %>
    <fieldset class="form-group">
        <%= telephone_field_tag 'number', '+1', class: 'form-control' %>
    </fieldset>
    <fieldset class="form-group">
        <%= text_field_tag 'message', 'Enter message here', class: 'form-control' %>
    </fieldset>
    <fieldset class="form-group">
        <%= submit_tag 'Send', class: 'btn btn-primary' %>
    </fieldset>
<% end %>

app/views/twillio/test.html.erb
<h1>Success, the message was sent!</h1>
<hr>
<%= params[:message] %><br>
sent to : <%= params[:number] %>